spring:
  application:
    name: base_project
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

kss:
  enable:
    swagger: true
  swagger:
    title: day la tittle
    body: day la body
    desc: desc
    email: kss_dev@kss.com.vn
    license: 1.0
    version: 1.0
    git-url: git_kss@gitlab
    contract:
      url: git_profile_dev@github.com
      name: dev_name
      email: email_devname

management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
