spring:
  application:
    name: base_project
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


kss:
  enable:
    swagger: true
  swagger:
    title: day la tittle
    body: day la body
    desc: desc
    email: manh.dd@kss.com.vn
    license: 1.0
    version: 1.0
    git-url: git@123
    contract:
      url: 3123123
      name: 3123123
      email: 2131312
logging:
  level:
    root: info
